landing/urls.py
from django.contrib import admin
from django.urls import path
from . import views

app_name = "landing"

urlpatterns = [
    path('gallery/', views.gallery),
    path('edu/', views.edu),
    path('skills/', views.skills),
    path('', views.home),
]

scheduler/templates/landing/urls.py
from django.urls import path, include
from landing.views import index
from landing.views import add_product
from landing.views import see_desc
from django.conf import settings
from django.conf.urls.static import static

app_name = "landing"

urlpatterns = [
    path("", index, name='index'),
    path("addproduct/", add_product, name='add_my_product'),
    path("desc/<int:id>/", see_desc, name="description")
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

scheduler/templates/makeschedule/landing/urls.py
from django.urls import path, include
from landing.views import index
from landing.views import add_product
from landing.views import see_desc
from django.conf import settings
from django.conf.urls.static import static

app_name = "landing"

urlpatterns = [
    path("", index, name='index'),
    path("addproduct/", add_product, name='add_my_product'),
    path("desc/<int:id>/", see_desc, name="description")
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

story/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib.staticfiles.urls import staticfiles_urlpatterns

urlpatterns = [
    path('admin/', admin.site.urls),
    path('scheduler/', include('scheduler.urls')), 
    path('', include("landing.urls")), 
    path('learnajax/', include("learn_ajax.urls")),   
    path('learnauth', include('learn_auth.urls')),
]

landing/models.py
from django.db import models

# Create your models here.

scheduler/templates/landing/models.py
from django.db import models

class Product(models.Model):
    name = models.TextField()
    imgProduct = models.ImageField(upload_to = "images/", default="static/default/default.jpg")
    price = models.IntegerField()
    category = models.TextField()
    description = models.TextField()

scheduler/templates/makeschedule/landing/models.py
from django.db import models

class Product(models.Model):
    name = models.TextField()
    imgProduct = models.ImageField(upload_to = "images/")
    price = models.IntegerField()
    category = models.TextField()
    description = models.TextField()

scheduler/templates/landing/forms.py
from django import forms
from .models import Product

class MakeProduct(forms.ModelForm):
    
    name = forms.CharField(
        label = "name", widget = forms.TextInput(attrs={
            "class" : "form-control",
            "type" : "text",
            "aria-label" : "Default",
            "aria-describedby" : "inputGroup-sizing-default"
        }),

    )

    imgProduct = forms.ImageField(
        label = "imgProduct",
        widget = forms.FileInput(attrs={
            "class" : "form-control",
            "type" : "file",
            "aria-label" : "Default",
            "aria-describedby" : "inputGroup-sizing-default",            
        })
    )

    category = forms.ChoiceField(
        label = "category", 
        
        choices = [
            ("Pets", "Pets"),
            ("Toys", "Toys"),
            ("Foods", "Foods"),
            ("Others", "Others"),
            ],

        widget = forms.Select(attrs = {
            "class" : "form-control",
            "type" : "text",
            "aria-label" : "Default",
            "aria-describedby" : "inputGroup-sizing-default",
        })
    )

    price = forms.IntegerField(
        label = "price",
        widget = forms.NumberInput(attrs={
            "class" : "form-control",
            "type" : "text",
            "aria-label" : "Default",
            "aria-describedby" : "inputGroup-sizing-default",

        })
    )

    description = forms.CharField(
        label = "description", widget = forms.Textarea(attrs={
            "class" : "form-control",
            "type" : "text",
            "aria-label" : "Default",
            "aria-describedby" : "inputGroup-sizing-default",
        })
    )
   
    class Meta:
        model = Product
        fields = ["name", "price", "imgProduct" , "category", "description"]

scheduler/templates/makeschedule/landing/forms.py
from django import forms
from .models import Product

class MakeProduct(forms.ModelForm):
    
    name = forms.CharField(
        label = "name", widget = forms.TextInput(attrs={
            "class" : "form-control",
            "type" : "text",
            "aria-label" : "Default",
            "aria-describedby" : "inputGroup-sizing-default"
        }),

    )

    imgProduct = forms.ImageField(
        label = "imgProduct",
        widget = forms.FileInput(attrs={
            "class" : "form-control",
            "type" : "file",
            "aria-label" : "Default",
            "aria-describedby" : "inputGroup-sizing-default",            
        })
    )

    category = forms.ChoiceField(
        label = "category", 
        
        choices = [
            ("Pets", "Pets"),
            ("Toys", "Toys"),
            ("Foods", "Foods"),
            ("Others", "Others"),
            ],

        widget = forms.Select(attrs = {
            "class" : "form-control",
            "type" : "text",
            "aria-label" : "Default",
            "aria-describedby" : "inputGroup-sizing-default",
        })
    )

    price = forms.IntegerField(
        label = "price",
        widget = forms.NumberInput(attrs={
            "class" : "form-control",
            "type" : "text",
            "aria-label" : "Default",
            "aria-describedby" : "inputGroup-sizing-default",

        })
    )

    description = forms.CharField(
        label = "description", widget = forms.Textarea(attrs={
            "class" : "form-control",
            "type" : "text",
            "aria-label" : "Default",
            "aria-describedby" : "inputGroup-sizing-default",
        })
    )
   
    class Meta:
        model = Product
        fields = ["name", "price", "imgProduct" , "category", "description"]

landing/views.py
from django.http import HttpResponse
from django.shortcuts import render

def home(request):
    return render(request, 'home.html')
    
def edu(request):
    return render(request, 'edu.html')


def skills(request):
    return render(request, 'skills.html')
    

def gallery(request):
    return render(request, 'galeri.html')

def scheduler(request):
    return render(request, 'scheduler.html')

scheduler/templates/landing/views.py
from django.shortcuts import render, redirect
from .models import Product
from .forms import MakeProduct


def see_desc(request, id):
    arg = Product.objects.get(pk=id)
    context = {
        "barang" : arg,
        "page_title" : arg.name
    }
    return render(request, "landing/desc.html", context)

def index(request):

    all_product = Product.objects.all().order_by("-id")
    arguments = {
        "page_title" : "Welcome to Your Pets",
        "products" : all_product,
        "top3" : all_product[:3:],
    }
    return render(request, "landing/landing_page.html", arguments)

def add_product(request):
    a_form = MakeProduct(request.POST or None, request.FILES or None)
    
    arguments = {
        "page_title" : "Add a Product",
        "form" : a_form,
    }

    if request.method == "POST" :
        if a_form.is_valid():
            a_form.save()
            return redirect("landing:add_my_product")
        else:
            a_form = MakeProduct()

    return render(request,"landing/addproduct.html", arguments)

scheduler/templates/makeschedule/landing/views.py
from django.shortcuts import render, redirect
from .models import Product
from .forms import MakeProduct


def see_desc(request, id):
    arg = Product.objects.get(pk=id)
    context = {
        "barang" : arg,
        "page_title" : arg.name
    }
    return render(request, "landing/desc.html", context)

def index(request):

    all_product = Product.objects.all().order_by("-id")
    arguments = {
        "page_title" : "Welcome to Your Pets",
        "products" : all_product,
        "top3" : all_product[:3:],
    }
    return render(request, "landing/landing_page.html", arguments)

def add_product(request):
    a_form = MakeProduct(request.POST or None, request.FILES or None)
    
    arguments = {
        "page_title" : "Add a Product",
        "form" : a_form,
    }

    if request.method == "POST" :
        if a_form.is_valid():
            a_form.save()
            return redirect("landing:add_my_product")
        else:
            a_form = MakeProduct()

    return render(request,"landing/addproduct.html", arguments)

scheduler/templates/makeschedule/landing/templates/landing/addproduct.html
{% extends 'landing/base.html' %}

{% load static %}


{% block style %}

{% endblock style %}



{% block content %}

<div class="container-fluid" style="margin-bottom: 5%;">
    <p class="text-center" style="font-size:200%;">Add Product</p>
</div>

<div class="container">
    <form action="{% url 'landing:add_my_product' %}" method="POST" enctype="multipart/form-data">
        {% csrf_token %}
        <div class="row">
            <div class="col">
                <div class="input-group mb-3">
                    <div class="input-group-prepend">
                        <span class="input-group-text" id="inputGroup-sizing-default">Name </span>
                    </div>
                    {{ form.name }}
                </div>
            </div>

            <div class="col">
                <div class="input-group mb-3">
                    <div class="input-group-prepend">
                        <span class="input-group-text" id="inputGroup-sizing-default">Image </span>
                    </div>
                    {{ form.imgProduct }}
                </div>
            </div>
        </div>
        
        <div class="row">
            <div class="col">
                <div class="input-group mb-3">
                    <div class="input-group-prepend">
                        <span class="input-group-text" id="inputGroup-sizing-default">Price</span>
                    </div>
                    {{ form.price }}
                </div>
            </div>

            <div class="col">
                <div class="input-group mb-3">
                    <div class="input-group-prepend">
                        <span class="input-group-text" id="inputGroup-sizing-default">Category</span>
                    </div>
                    {{ form.category }}
                </div>
            </div>
        </div>

        <div class="row">
            <div class="col">
                <p class="input-group-text" id="inputGroup-sizing-default">Description</p>
                {{ form.description }}
            </div>
        </div>

        <div class="row">
            <div class="col">
                <button type="submit" style="margin-top: 2%;">Add This Product</button>
            </div>
        </div>
                        
    </form>

</div>




{% endblock content %}

scheduler/templates/makeschedule/landing/templates/landing/base.html
<!doctype html>
{% load static %}
<html lang="en">
    <head>
        <!-- Required meta tags -->
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

        <!-- Bootstrap CSS -->
        {% include 'landing/snippets/bootstrap.html' %}

        {% block style %}

        {% endblock style %}
        
        <title>{{ page_title }}</title>
    </head>
    <body>
        <div id="navbar">
            {% include 'landing/snippets/navbar.html' %}
        </div>
        <div>
            {% block content %}

            {% endblock content %}
        </div>

        <!-- Optional JavaScript -->
        <!-- jQuery first, then Popper.js, then Bootstrap JS -->
        {% include 'landing/snippets/bootstrapjquerypopper.html' %}
    </body>
</html>

scheduler/templates/makeschedule/landing/templates/landing/desc.html
{% extends 'landing/base.html' %}

{% load static %}

{% block style %}
<link rel="stylesheet" href="{% static 'css/landing.css' %}">
{% endblock style %}


{% block content %}

<div class="container" style="margin-bottom: 20px; margin-top: 10px;">
    <div class="page-header">
        <h1>{{ barang.name }}</h1>
    </div>
</div>

<div class="container">
    <div class="row">
        <div class="col">
            <img src="{{ barang.imgProduct.url }}" style="border-radius: 10%;" alt="Gambar Produk">
        </div>
        <div class="col">
            <a href="#" class="btn btn-secondary btn-lg" tabindex="-1" role="button" aria-disabled="true">Beli Produk Ini</a>
            <p style="font-size: 3rem;">IDR {{ barang.price }}</p>
        </div>
    </div>        
</div>

<div class="container">
    <div class="row">
        <div class="col">
            <p class="text-center"><br>{{ barang.description }}</p>
        </div>
        <div class="col">
        </div>
    </div>
</div>
{% endblock content %}

scheduler/templates/makeschedule/landing/templates/landing/landing_page.html
{% extends 'landing/base.html' %}

{% load static %}

{% block style %}
<link rel="stylesheet" href="{% static 'css/landing.css' %}">
{% endblock style %}


{% block content %}

<div class="container-fluid">
    <p class="text-center" style="font-family: muli; font-size: 2rem; margin-bottom: 5rem; margin-top: 1rem;">Welcome,
        <br>Let's find your pets and their needs here...</p>
</div>

<div class="container-fluid" id="newest_product" style="background-color: #F7F4F3;">
    <div>
        <br>
        <h1 style="font-family: muli;">Our Newest Products</h1>
        <br>
    </div>
    
    <div class="row">
        {% for i in top3 %}
            <div class="col">
                <img src="{{ i.imgProduct.url }}" style="border-radius: 5%;" 
                class="img-fluid" alt="Gambar Produk"/>
                <!-- <p>{{ i.name }}</p> -->
                <a href="{% url 'landing:description' i.id %}"> {{ i.name }}</a>
                <p>IDR {{ i.price }}</p>
            </div>
        {% endfor %}
    </div>
    <br>

</div>


<div class="container-fluid"  id="for_all_product" style="margin-bottom:5rem;">
    <div>
        <br><br><h1 style="font-family: muli;">All Products</h1><br>
    </div>

    <div class="row">
    {% for product in products %}
        <div class="card mx-3 my-2" style="width: 18rem;">
            <img src="{{ product.imgProduct.url }}" class="card-img-top" alt="Gambar Produk">
            <div class="card-body">
                <h5 class="card-title">{{ product.name }}<br>IDR {{ product.price }}</h5>
                <p class="card-text">{{ product.description }}</p>
                <div class="mt-auto p-2 bd-highlight">
                    <a href="{% url 'landing:description' product.id %}" class="btn btn-primary pull-right" style="float: left;">Lihat</a>
                </div>
            </div>
        </div>
    {% endfor %}
    </div>
</div>

<div class="container-fluid" id="footer" style="background-color: #F7F4F3; padding-bottom: 1rem;">
        <a href="{% url 'landing:add_my_product' %}" class="btn btn-secondary btn-lg" tabindex="-1" role="button" aria-disabled="true">Add Product</a>
</div>

{% endblock content %}