landing/urls.py
from django.contrib import admin
from django.urls import path
from . import views

app_name = "landing"

urlpatterns = [
    path('gallery/', views.gallery),
    path('edu/', views.edu),
    path('skills/', views.skills),
    path('', views.home),
]

scheduler/templates/landing/urls.py
from django.urls import path, include
from landing.views import index
from landing.views import add_product
from landing.views import see_desc
from django.conf import settings
from django.conf.urls.static import static

app_name = "landing"

urlpatterns = [
    path("", index, name='index'),
    path("addproduct/", add_product, name='add_my_product'),
    path("desc/<int:id>/", see_desc, name="description")
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

scheduler/templates/makeschedule/landing/urls.py
from django.urls import path, include
from landing.views import index
from landing.views import add_product
from landing.views import see_desc
from django.conf import settings
from django.conf.urls.static import static

app_name = "landing"

urlpatterns = [
    path("", index, name='index'),
    path("addproduct/", add_product, name='add_my_product'),
    path("desc/<int:id>/", see_desc, name="description")
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

story/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib.staticfiles.urls import staticfiles_urlpatterns

urlpatterns = [
    path('admin/', admin.site.urls),
    path('scheduler/', include('scheduler.urls')), 
    path('', include("landing.urls")), 
    path('learnajax/', include("learn_ajax.urls")),   
    path('learnauth', include('learn_auth.urls')),
]

landing/models.py
from django.db import models

# Create your models here.

scheduler/templates/landing/models.py
from django.db import models

class Product(models.Model):
    name = models.TextField()
    imgProduct = models.ImageField(upload_to = "images/", default="static/default/default.jpg")
    price = models.IntegerField()
    category = models.TextField()
    description = models.TextField()

scheduler/templates/makeschedule/landing/models.py
from django.db import models

class Product(models.Model):
    name = models.TextField()
    imgProduct = models.ImageField(upload_to = "images/")
    price = models.IntegerField()
    category = models.TextField()
    description = models.TextField()

scheduler/templates/landing/forms.py
from django import forms
from .models import Product

class MakeProduct(forms.ModelForm):
    
    name = forms.CharField(
        label = "name", widget = forms.TextInput(attrs={
            "class" : "form-control",
            "type" : "text",
            "aria-label" : "Default",
            "aria-describedby" : "inputGroup-sizing-default"
        }),

    )

    imgProduct = forms.ImageField(
        label = "imgProduct",
        widget = forms.FileInput(attrs={
            "class" : "form-control",
            "type" : "file",
            "aria-label" : "Default",
            "aria-describedby" : "inputGroup-sizing-default",            
        })
    )

    category = forms.ChoiceField(
        label = "category", 
        
        choices = [
            ("Pets", "Pets"),
            ("Toys", "Toys"),
            ("Foods", "Foods"),
            ("Others", "Others"),
            ],

        widget = forms.Select(attrs = {
            "class" : "form-control",
            "type" : "text",
            "aria-label" : "Default",
            "aria-describedby" : "inputGroup-sizing-default",
        })
    )

    price = forms.IntegerField(
        label = "price",
        widget = forms.NumberInput(attrs={
            "class" : "form-control",
            "type" : "text",
            "aria-label" : "Default",
            "aria-describedby" : "inputGroup-sizing-default",

        })
    )

    description = forms.CharField(
        label = "description", widget = forms.Textarea(attrs={
            "class" : "form-control",
            "type" : "text",
            "aria-label" : "Default",
            "aria-describedby" : "inputGroup-sizing-default",
        })
    )
   
    class Meta:
        model = Product
        fields = ["name", "price", "imgProduct" , "category", "description"]

scheduler/templates/makeschedule/landing/forms.py
from django import forms
from .models import Product

class MakeProduct(forms.ModelForm):
    
    name = forms.CharField(
        label = "name", widget = forms.TextInput(attrs={
            "class" : "form-control",
            "type" : "text",
            "aria-label" : "Default",
            "aria-describedby" : "inputGroup-sizing-default"
        }),

    )

    imgProduct = forms.ImageField(
        label = "imgProduct",
        widget = forms.FileInput(attrs={
            "class" : "form-control",
            "type" : "file",
            "aria-label" : "Default",
            "aria-describedby" : "inputGroup-sizing-default",            
        })
    )

    category = forms.ChoiceField(
        label = "category", 
        
        choices = [
            ("Pets", "Pets"),
            ("Toys", "Toys"),
            ("Foods", "Foods"),
            ("Others", "Others"),
            ],

        widget = forms.Select(attrs = {
            "class" : "form-control",
            "type" : "text",
            "aria-label" : "Default",
            "aria-describedby" : "inputGroup-sizing-default",
        })
    )

    price = forms.IntegerField(
        label = "price",
        widget = forms.NumberInput(attrs={
            "class" : "form-control",
            "type" : "text",
            "aria-label" : "Default",
            "aria-describedby" : "inputGroup-sizing-default",

        })
    )

    description = forms.CharField(
        label = "description", widget = forms.Textarea(attrs={
            "class" : "form-control",
            "type" : "text",
            "aria-label" : "Default",
            "aria-describedby" : "inputGroup-sizing-default",
        })
    )
   
    class Meta:
        model = Product
        fields = ["name", "price", "imgProduct" , "category", "description"]

landing/views.py
from django.http import HttpResponse
from django.shortcuts import render

def home(request):
    return render(request, 'home.html')
    
def edu(request):
    return render(request, 'edu.html')


def skills(request):
    return render(request, 'skills.html')
    

def gallery(request):
    return render(request, 'galeri.html')

def scheduler(request):
    return render(request, 'scheduler.html')

scheduler/templates/landing/views.py
from django.shortcuts import render, redirect
from .models import Product
from .forms import MakeProduct


def see_desc(request, id):
    arg = Product.objects.get(pk=id)
    context = {
        "barang" : arg,
        "page_title" : arg.name
    }
    return render(request, "landing/desc.html", context)

def index(request):

    all_product = Product.objects.all().order_by("-id")
    arguments = {
        "page_title" : "Welcome to Your Pets",
        "products" : all_product,
        "top3" : all_product[:3:],
    }
    return render(request, "landing/landing_page.html", arguments)

def add_product(request):
    a_form = MakeProduct(request.POST or None, request.FILES or None)
    
    arguments = {
        "page_title" : "Add a Product",
        "form" : a_form,
    }

    if request.method == "POST" :
        if a_form.is_valid():
            a_form.save()
            return redirect("landing:add_my_product")
        else:
            a_form = MakeProduct()

    return render(request,"landing/addproduct.html", arguments)

scheduler/templates/makeschedule/landing/views.py
from django.shortcuts import render, redirect
from .models import Product
from .forms import MakeProduct


def see_desc(request, id):
    arg = Product.objects.get(pk=id)
    context = {
        "barang" : arg,
        "page_title" : arg.name
    }
    return render(request, "landing/desc.html", context)

def index(request):

    all_product = Product.objects.all().order_by("-id")
    arguments = {
        "page_title" : "Welcome to Your Pets",
        "products" : all_product,
        "top3" : all_product[:3:],
    }
    return render(request, "landing/landing_page.html", arguments)

def add_product(request):
    a_form = MakeProduct(request.POST or None, request.FILES or None)
    
    arguments = {
        "page_title" : "Add a Product",
        "form" : a_form,
    }

    if request.method == "POST" :
        if a_form.is_valid():
            a_form.save()
            return redirect("landing:add_my_product")
        else:
            a_form = MakeProduct()

    return render(request,"landing/addproduct.html", arguments)

scheduler/templates/makeschedule/landing/templates/landing/snippets/bootstrap.html
{% load static %}

<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">

scheduler/templates/makeschedule/landing/templates/landing/snippets/bootstrapjquerypopper.html
{% load static %}

<script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>

scheduler/templates/makeschedule/landing/templates/landing/snippets/navbar.html
{% load static %}

<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <a class="navbar-brand" style="padding-top:0; padding-bottom:.65rem;" href="{% url 'landing:index' %}">
  	<img src="{% static 'LogoYourPets.png'%}" alt="" style="max-width:8rem">
  </a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarNavDropdown">
    <ul class="navbar-nav">
      <li class="nav-item">
        <a class="nav-link" href="{% url 'landing:index' %}">Home</a>
      </li>
      <li class="nav-item dropdown">
        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdownMenuLink" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          More
        </a>
        <div class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
          <a class="dropdown-item" href="{% url 'list_testimoni' %}">Testimoni</a>
          <a class="dropdown-item" href="#">FAQs</a>    
		  <a class="dropdown-item" href="#">Pembayaran</a>       
        </div>
      </li>
    </ul>
  </div>
</nav>