learn_auth/urls.py
from django.urls import path
from .views import login_page, success_page, logout_account

app_name = "learn_auth"

urlpatterns = [
    path('/', login_page, name="login_page"),
    path('/success/', success_page, name="success_page"),
    path('/success_logout', logout_account, name='logout_user')
]

story/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib.staticfiles.urls import staticfiles_urlpatterns

urlpatterns = [
    path('admin/', admin.site.urls),
    path('scheduler/', include('scheduler.urls')), 
    path('', include("landing.urls")), 
    path('learnajax/', include("learn_ajax.urls")),   
    path('learnauth', include('learn_auth.urls')),
]

learn_auth/models.py
from django.db import models

# Create your models here.

learn_auth/views.py
from django.shortcuts import render
from django.shortcuts import render, redirect
from django.contrib.auth import login, logout, authenticate
from django.contrib.auth.forms import AuthenticationForm,UserCreationForm
from django.contrib.auth.decorators import login_required



def login_page(request):
    if request.user.is_authenticated:
        return redirect('learn_auth:success_page')
    
    if request.method == "POST":
        form = AuthenticationForm(data=request.POST)
        if form.is_valid():
            user = form.get_user()
            login(request,user)
            request.session["user"] = request.POST["username"]
            return redirect("learn_auth:success_page")
    
    form = AuthenticationForm()
    return render(request, "index_auth.html", {"form": form })

@login_required(login_url="learn_auth:login_page")
def success_page(request):
    username = request.session.get("user")
    return render(request, "success.html", {"username" : username})


def logout_account(request):
    if request.method == "POST":
        logout(request)
    return redirect("learn_auth:login_page")

learn_auth/templates/index_auth.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <title>Please Login</title>
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
</head>
<body>
    <div class="container" style="margin: 15px;">
      <form action="{% url 'learn_auth:login_page' %}" method="POST">
        {% csrf_token %}
        {{ form }}
        <button type="submit">Login</button>
      </form>
    </div>
</body>
</html>

learn_auth/templates/success.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Success, yeayy!</title>
</head>
<body>
    <h1>
        Hello, {{ username }}. <br>
        Selamat, kamu berhasil Login di web iniii....
    </h1>

    <form action="{% url 'learn_auth:logout_user' %}" method="POST">
        {% csrf_token %}
        <button type="submit">Logout</button>
    </form>
    
</body>
</html>