scheduler/templates/landing/urls.py
from django.urls import path, include
from landing.views import index
from landing.views import add_product
from landing.views import see_desc
from django.conf import settings
from django.conf.urls.static import static

app_name = "landing"

urlpatterns = [
    path("", index, name='index'),
    path("addproduct/", add_product, name='add_my_product'),
    path("desc/<int:id>/", see_desc, name="description")
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

scheduler/templates/makeschedule/barang/urls.py
from django.urls import path
# from barang.views import <namamethod>

urlpatterns = [

]

scheduler/urls.py
from django.urls import path
from . import views
from django.contrib.staticfiles.urls import staticfiles_urlpatterns

app_name = 'scheduler'

urlpatterns = [
    path('', views.make_schedule, name='make_schedule'),
    path('delete/<int:id>/', views.delete, name="delete"),
]

urlpatterns += staticfiles_urlpatterns()

story/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib.staticfiles.urls import staticfiles_urlpatterns

urlpatterns = [
    path('admin/', admin.site.urls),
    path('scheduler/', include('scheduler.urls')), 
    path('', include("landing.urls")), 
    path('learnajax/', include("learn_ajax.urls")),   
    path('learnauth', include('learn_auth.urls')),
]

scheduler/models.py
from django.db import models
from django.utils import timezone
from datetime import datetime, date

class Activities(models.Model):

    activity = models.CharField(max_length=100)
    date = models.DateField()
    time = models.TimeField()
    place = models.TextField()
    category = models.TextField()
    

scheduler/templates/landing/models.py
from django.db import models

class Product(models.Model):
    name = models.TextField()
    imgProduct = models.ImageField(upload_to = "images/", default="static/default/default.jpg")
    price = models.IntegerField()
    category = models.TextField()
    description = models.TextField()

scheduler/templates/makeschedule/barang/models.py
from django.db import models

# Create your models here.

scheduler/templates/makeschedule/landing/models.py
from django.db import models

class Product(models.Model):
    name = models.TextField()
    imgProduct = models.ImageField(upload_to = "images/")
    price = models.IntegerField()
    category = models.TextField()
    description = models.TextField()

scheduler/forms.py
from django import forms
from scheduler import models


class Scheduler(forms.Form):
    activity = forms.CharField(
        label='activity',  widget=forms.TextInput(attrs={
        'class' : "form-control",
        'type' : "text",
        'aria-label' : "Default",
        'aria-describedby' : "inputGroup-sizing-default",
        }), max_length=50)

    place = forms.CharField(label='place', widget=forms.TextInput(attrs={
        'class' : "form-control",
        'type' : "text",
        'aria-label' : "Default",
        'aria-describedby' : "inputGroup-sizing-default",
        }))

    category = forms.ChoiceField(
        label='category', 
        choices=[('Akademik', 'Akademik'),
            ('Personal', 'Personal'),
            ('Keluarga', 'Keluarga'),
            ('Lainnya', 'Lainnya')],
        widget=forms.Select(attrs={
        'class' : "form-control",
        'type' : "text",
        'aria-label' : "Default",
        'aria-describedby' : "inputGroup-sizing-default",
        }))

    date = forms.DateField(label="date", widget=forms.DateInput(attrs={
        'class' : "form-control",
        'type' : "date",
        'aria-label' : "Default",
        'aria-describedby' : "inputGroup-sizing-default",
        }))
    
    time = forms.TimeField(label="time", widget=forms.TimeInput(attrs={
        'class' : "form-control",
        'type' : "time",
        'aria-label' : "Default",
        'aria-describedby' : "inputGroup-sizing-default",
        }))
    
    class Meta:
        model = models.Activities
        fields = ['activity', 'place', 'category', 'date', 'time']

scheduler/templates/landing/forms.py
from django import forms
from .models import Product

class MakeProduct(forms.ModelForm):
    
    name = forms.CharField(
        label = "name", widget = forms.TextInput(attrs={
            "class" : "form-control",
            "type" : "text",
            "aria-label" : "Default",
            "aria-describedby" : "inputGroup-sizing-default"
        }),

    )

    imgProduct = forms.ImageField(
        label = "imgProduct",
        widget = forms.FileInput(attrs={
            "class" : "form-control",
            "type" : "file",
            "aria-label" : "Default",
            "aria-describedby" : "inputGroup-sizing-default",            
        })
    )

    category = forms.ChoiceField(
        label = "category", 
        
        choices = [
            ("Pets", "Pets"),
            ("Toys", "Toys"),
            ("Foods", "Foods"),
            ("Others", "Others"),
            ],

        widget = forms.Select(attrs = {
            "class" : "form-control",
            "type" : "text",
            "aria-label" : "Default",
            "aria-describedby" : "inputGroup-sizing-default",
        })
    )

    price = forms.IntegerField(
        label = "price",
        widget = forms.NumberInput(attrs={
            "class" : "form-control",
            "type" : "text",
            "aria-label" : "Default",
            "aria-describedby" : "inputGroup-sizing-default",

        })
    )

    description = forms.CharField(
        label = "description", widget = forms.Textarea(attrs={
            "class" : "form-control",
            "type" : "text",
            "aria-label" : "Default",
            "aria-describedby" : "inputGroup-sizing-default",
        })
    )
   
    class Meta:
        model = Product
        fields = ["name", "price", "imgProduct" , "category", "description"]

scheduler/templates/makeschedule/landing/forms.py
from django import forms
from .models import Product

class MakeProduct(forms.ModelForm):
    
    name = forms.CharField(
        label = "name", widget = forms.TextInput(attrs={
            "class" : "form-control",
            "type" : "text",
            "aria-label" : "Default",
            "aria-describedby" : "inputGroup-sizing-default"
        }),

    )

    imgProduct = forms.ImageField(
        label = "imgProduct",
        widget = forms.FileInput(attrs={
            "class" : "form-control",
            "type" : "file",
            "aria-label" : "Default",
            "aria-describedby" : "inputGroup-sizing-default",            
        })
    )

    category = forms.ChoiceField(
        label = "category", 
        
        choices = [
            ("Pets", "Pets"),
            ("Toys", "Toys"),
            ("Foods", "Foods"),
            ("Others", "Others"),
            ],

        widget = forms.Select(attrs = {
            "class" : "form-control",
            "type" : "text",
            "aria-label" : "Default",
            "aria-describedby" : "inputGroup-sizing-default",
        })
    )

    price = forms.IntegerField(
        label = "price",
        widget = forms.NumberInput(attrs={
            "class" : "form-control",
            "type" : "text",
            "aria-label" : "Default",
            "aria-describedby" : "inputGroup-sizing-default",

        })
    )

    description = forms.CharField(
        label = "description", widget = forms.Textarea(attrs={
            "class" : "form-control",
            "type" : "text",
            "aria-label" : "Default",
            "aria-describedby" : "inputGroup-sizing-default",
        })
    )
   
    class Meta:
        model = Product
        fields = ["name", "price", "imgProduct" , "category", "description"]

scheduler/templates/landing/views.py
from django.shortcuts import render, redirect
from .models import Product
from .forms import MakeProduct


def see_desc(request, id):
    arg = Product.objects.get(pk=id)
    context = {
        "barang" : arg,
        "page_title" : arg.name
    }
    return render(request, "landing/desc.html", context)

def index(request):

    all_product = Product.objects.all().order_by("-id")
    arguments = {
        "page_title" : "Welcome to Your Pets",
        "products" : all_product,
        "top3" : all_product[:3:],
    }
    return render(request, "landing/landing_page.html", arguments)

def add_product(request):
    a_form = MakeProduct(request.POST or None, request.FILES or None)
    
    arguments = {
        "page_title" : "Add a Product",
        "form" : a_form,
    }

    if request.method == "POST" :
        if a_form.is_valid():
            a_form.save()
            return redirect("landing:add_my_product")
        else:
            a_form = MakeProduct()

    return render(request,"landing/addproduct.html", arguments)

scheduler/templates/makeschedule/barang/views.py
from django.shortcuts import render

# Create your views here.

scheduler/templates/makeschedule/landing/views.py
from django.shortcuts import render, redirect
from .models import Product
from .forms import MakeProduct


def see_desc(request, id):
    arg = Product.objects.get(pk=id)
    context = {
        "barang" : arg,
        "page_title" : arg.name
    }
    return render(request, "landing/desc.html", context)

def index(request):

    all_product = Product.objects.all().order_by("-id")
    arguments = {
        "page_title" : "Welcome to Your Pets",
        "products" : all_product,
        "top3" : all_product[:3:],
    }
    return render(request, "landing/landing_page.html", arguments)

def add_product(request):
    a_form = MakeProduct(request.POST or None, request.FILES or None)
    
    arguments = {
        "page_title" : "Add a Product",
        "form" : a_form,
    }

    if request.method == "POST" :
        if a_form.is_valid():
            a_form.save()
            return redirect("landing:add_my_product")
        else:
            a_form = MakeProduct()

    return render(request,"landing/addproduct.html", arguments)

scheduler/views.py
from django.shortcuts import render, redirect
from .models import Activities
from . import forms
from .forms import Scheduler
from datetime import datetime


def make_schedule(request):
    form = Scheduler(request.POST)

    if request.method == "POST":
        if form.is_valid():
            new = Activities(
                activity = form.data['activity'],
                place = form.data['place'],
                date = form.data['date'],
                time = form.data['time'],
                category = form.data['category'],
                )
            new.save()
            return redirect('scheduler:make_schedule')
        else :
            form = form.Scheduler()
    schedule = Activities.objects.all().values()
    argument = {
        'schedules_active' : 'active',
        'context' : {'now': datetime.now()},
        'jadwalgue': schedule,
        'form' : form,

    }
    return render(request, 'makeschedule/scheduler.html', argument)

def delete(request, id):   
    Activities.objects.get(pk=id).delete()
    return redirect('scheduler:make_schedule')

scheduler/templates/makeschedule/navbar.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Welcome to My Home</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'index.css' %}">
</head>

<body>
    <nav class="navbar navbar-expand-lg fixed-top navbar-dark" style="background-color: #01977F">
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarNavDropdown">
            <ul class="navbar-nav" style="font-family:cursive; font-size: 130%;">
                <li class="nav-item">
                    <a class="nav-link" href="/">Home</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="/edu">Education & Experiences</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="/skills">Skills & Language</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="/gallery">Gallery</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="/scheduler">Scheduler</a>
                </li>

            </ul>
        </div>
    </nav>
    {% block content %}
    
    {% endblock %}
    
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
</body>
</html>

scheduler/templates/makeschedule/scheduler.html
{% extends 'navbar.html' %}

{% block content %}
<br><br><br><br><br><br><br>
<div class="container-fluid">
    <form action="{% url 'scheduler:make_schedule' %}" method="POST">
        {% csrf_token %}
        <div class="row">
            <div class="col">
                <div class="input-group mb-3">
                    <div class="input-group-prepend">
                        <span class="input-group-text" id="inputGroup-sizing-default">Activity:</span>
                    </div>
                    {{ form.activity }}
                </div>

            </div>
            <div class="col">
                <div class="input-group mb-3">
                    <div class="input-group-prepend">
                        <span class="input-group-text" id="inputGroup-sizing-default">Category:</span>
                    </div>
                    {{ form.category }}
                </div>
            </div>
        </div>

        <div class="input-group mb-3">
            <div class="input-group-prepend">
                <span class="input-group-text" id="inputGroup-sizing-default">Place:</span>
            </div>
            {{ form.place }}
        </div>

        <div class="row">
            <div class="col">
                <div class="input-group mb-3">
                    <div class="input-group-prepend">
                        <span class="input-group-text" id="inputGroup-sizing-default">Date:</span>
                    </div>
                    {{ form.date }}
                </div>
            </div>

            <div class="col">
                <div class="input-group mb-3">
                    <div class="input-group-prepend">
                        <span class="input-group-text" id="inputGroup-sizing-default">Time:</span>
                    </div>
                    {{ form.time }}
                </div>
            </div>
        </div>
        <button type="submit">Add Schedule</button>
        
    </form>
</div>


<div class="container-fluid">
    <div class="schedule">
        {% for i in jadwalgue %}
            <div class="each_schedule">
                <h3>{{ i.activity }}</h3>
                <p>Category : {{ i.category }} </p>
                <p>Date : {{ i.date }} , {{ i.time }}</p>
                <p>Place : {{ i.place }} </p>
                <a href="{% url 'scheduler:delete' i.id %}" >Delete</a>
            </div>
        {% endfor %}
    </div>
</div>

{% endblock %}